#%RAML 1.0 DataType
description: Request data type for user account
type: object

properties:
  username:
    type: string
    example: JuliusSauco
  email:
    type: string
    example: julius.sauco@gmail.com
  password:
    type: string
    example: ~g3hr)1$;)O!lA'K1a2wdw,5