#%RAML 1.0 Library
usage: Library for authentication data types in Olympus Platform

types:
  UserAccountRequest: !include account/request/post-user-account-request.raml
  SignInRequest: !include session/request/post-sign-in-request.raml
  SignUpRequest: !include session/request/post-sign-up-request.raml