#%RAML 1.0 Library
usage: Groups all the traits corresponding to the API.

traits:
  SecuredCIE: !include traits/secure-cie.raml
  SecuredJWT: !include traits/secure-jwt.raml
  ConfigSession: !include config/config-session.raml