#%RAML 1.0 DocumentationItem
title: Olympus Platform - Authentication System API
content: |

  The **System API (SAPI) for integration with authentication services** allows the channel to exchange information with the different legacy systems that make up the solution in a simple and efficient way. It is designed to connect specifically to the services required to carry out client requests, so its endpoints and objects are built according to the information required by said channel.